# Generated by Django 6.0.6 on 2026-06-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
